name: extended_text_library
description: package library for extended_text and extended_text_field,provide common base class.
version: 9.1.1
homepage: https://github.com/fluttercandies/extended_text_library

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_text_field:
    git: https://github.com/xwdevhub/extended_text_field.git

